### ISSUE TITLE
NPE when rapidly changing member suggestions drop down

### ISSUE THREAD

**Issue by peter-tackage** [peter-tackage/open-secret-santa#17]
06-30 11:04:10.114: I/SuggestionsAdapter(29388): autoComplete() - cursor length: 0
06-30 11:04:10.114: I/SuggestionsAdapter(29388): autoComplete() - cursor cols: [display_name, data1, contact_id, photo_thumb_uri, lookup]
06-30 11:04:10.134: I/SuggestionsAdapter(29388): autoComplete() - cursor length: 0
06-30 11:04:10.134: I/SuggestionsAdapter(29388): autoComplete() - cursor cols: [display_name, data1, contact_id, photo_thumb_uri, lookup]
06-30 11:04:10.144: D/AndroidRuntime(29388): Shutting down VM
06-30 11:04:10.144: W/dalvikvm(29388): threadid=1: thread exiting with uncaught exception (group=0x417e4930)
06-30 11:04:10.154: E/AndroidRuntime(29388): FATAL EXCEPTION: main
06-30 11:04:10.154: E/AndroidRuntime(29388): java.lang.IndexOutOfBoundsException: Invalid index 2, size is 1
06-30 11:04:10.154: E/AndroidRuntime(29388):    at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:251)
06-30 11:04:10.154: E/AndroidRuntime(29388):    at java.util.ArrayList.get(ArrayList.java:304)
06-30 11:04:10.154: E/AndroidRuntime(29388):    at com.moac.android.opensecretsanta.adapter.SuggestionsAdapter.getView(SuggestionsAdapter.java:74)
06-30 11:04:10.154: E/AndroidRuntime(29388):    at android.widget.AbsListView.obtainView(AbsListView.java:2143)
06-30 11:04:10.154: E/AndroidRuntime(29388):    at android.widget.ListPopupWindow$DropDownListView.obtainView(ListPopupWindow.java:1196)
06-30 11:04:10.154: E/AndroidRuntime(29388):    at android.widget.ListView.measureHeightOfChildren(ListView.java:1246)
06-30 11:04:10.154: E/AndroidRuntime(29388):    at android.widget.ListPopupWindow.buildDropDown(ListPopupWindow.java:1123)
06-30 11:04:10.154: E/AndroidRuntime(29388):    at android.widget.ListPopupWindow.show(ListPopupWindow.java:532)
06-30 11:04:10.154: E/AndroidRuntime(29388):    at android.widget.ListPopupWindow$PopupDataSetObserver.onChanged(ListPopupWindow.java:1247)
06-30 11:04:10.154: E/AndroidRuntime(29388):    at android.database.DataSetObservable.notifyChanged(DataSetObservable.java:37)
06-30 11:04:10.154: E/AndroidRuntime(29388):    at android.widget.BaseAdapter.notifyDataSetChanged(BaseAdapter.java:50)
06-30 11:04:10.154: E/AndroidRuntime(29388):    at com.moac.android.opensecretsanta.adapter.SuggestionsAdapter$1.publishResults(SuggestionsAdapter.java:114)
06-30 11:04:10.154: E/AndroidRuntime(29388):    at android.widget.Filter$ResultsHandler.handleMessage(Filter.java:282)
06-30 11:04:10.154: E/AndroidRuntime(29388):    at android.os.Handler.dispatchMessage(Handler.java:99)
06-30 11:04:10.154: E/AndroidRuntime(29388):    at android.os.Looper.loop(Looper.java:137)
06-30 11:04:10.154: E/AndroidRuntime(29388):    at android.app.ActivityThread.main(ActivityThread.java:5041)
06-30 11:04:10.154: E/AndroidRuntime(29388):    at java.lang.reflect.Method.invokeNative(Native Method)
06-30 11:04:10.154: E/AndroidRuntime(29388):    at java.lang.reflect.Method.invoke(Method.java:511)
06-30 11:04:10.154: E/AndroidRuntime(29388):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
06-30 11:04:10.154: E/AndroidRuntime(29388):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
06-30 11:04:10.154: E/AndroidRuntime(29388):    at dalvik.system.NativeStart.main(Native Method)

**Comment by peter-tackage** [comment]
Also

```
11-12 10:31:11.254: ERROR/AndroidRuntime(10076): FATAL EXCEPTION: main
    java.lang.IndexOutOfBoundsException: Invalid index 2, size is 1
    at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
    at java.util.ArrayList.get(ArrayList.java:308)
    at com.moac.android.opensecretsanta.adapter.SuggestionsAdapter.getView(SuggestionsAdapter.java:74)
    at android.widget.AbsListView.obtainView(AbsListView.java:2161)
    at android.widget.ListPopupWindow$DropDownListView.obtainView(ListPopupWindow.java:1196)
    at android.widget.ListView.measureHeightOfChildren(ListView.java:1247)
    at android.widget.ListPopupWindow.buildDropDown(ListPopupWindow.java:1123)
    at android.widget.ListPopupWindow.show(ListPopupWindow.java:532)
    at android.widget.AutoCompleteTextView.showDropDown(AutoCompleteTextView.java:1096)
    at android.widget.AutoCompleteTextView.updateDropDownForFilter(AutoCompleteTextView.java:971)
    at android.widget.AutoCompleteTextView.onFilterComplete(AutoCompleteTextView.java:953)
    at android.widget.Filter$ResultsHandler.handleMessage(Filter.java:285)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:137)
    at android.app.ActivityThread.main(ActivityThread.java:5103)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:525)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:737)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
    at dalvik.system.NativeStart.main(Native Method)
```

**Comment by peter-tackage** [comment]
This has been fixed, the problem was due to the item lists that backs the Adapter being updated from the background thread that was generating the suggestions.
