### ISSUE TITLE
Null Pointer Exception when Member List updated during CAB selection

### ISSUE THREAD

**Issue by peter-tackage** [peter-tackage/open-secret-santa#48]
This has been reported via Google Play. I believe this scenario is caused when the SMS Broadcast Receiver for the SENT intent updates the list after the CAB mode has been set. The list is redrawn and perhaps invalidated. The stack dump is as follows -

```
java.lang.NullPointerException
at com.moac.android.opensecretsanta.d.c.onActionItemClicked(SourceFile:246)
at android.widget.AbsListView$MultiChoiceModeWrapper.onActionItemClicked(AbsListView.java:7674)
at com.android.internal.policy.impl.PhoneWindow$DecorView$ActionModeCallbackWrapper.onActionItemClicked(PhoneWindow.java:3299)
at com.android.internal.app.ActionBarImpl$ActionModeImpl.onMenuItemSelected(ActionBarImpl.java:1009)
at com.android.internal.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:735)
at com.android.internal.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:152)
at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:874)
at com.android.internal.view.menu.ActionMenuView.invokeItem(ActionMenuView.java:630)
at com.android.internal.view.menu.ActionMenuItemView.onClick(ActionMenuItemView.java:200)
at android.view.View.performClick(View.java:4475)
at android.view.View$PerformClick.run(View.java:18786)
at android.os.Handler.handleCallback(Handler.java:730)
at android.os.Handler.dispatchMessage(Handler.java:92)
at android.os.Looper.loop(Looper.java:137)
at android.app.ActivityThread.main(ActivityThread.java:5419)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:525)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1187)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
at dalvik.system.NativeStart.main(Native Method)
```

**Comment by peter-tackage** [comment]
The list being redrawn would mean that the currently checked items would be unchecked. If this were to occur without the CAB being updated, then there is a potential for failures when an ActionBar item is used.

**Comment by peter-tackage** [comment]
This occurs when changing between Groups without closing the CAB - 

```
04-07 22:28:07.976  20303-20303/? E/AndroidRuntime﹕ FATAL EXCEPTION: main
Process: com.moac.android.opensecretsanta, PID: 20303
java.lang.IllegalStateException: Content view not yet created
        at android.app.ListFragment.ensureList(ListFragment.java:386)
        at android.app.ListFragment.getListView(ListFragment.java:280)
        at com.moac.android.opensecretsanta.d.c.onActionItemClicked(SourceFile:246)
        at android.widget.AbsListView$MultiChoiceModeWrapper.onActionItemClicked(AbsListView.java:6343)
        at com.android.internal.policy.impl.PhoneWindow$DecorView$ActionModeCallbackWrapper.onActionItemClicked(PhoneWindow.java:2755)
        at com.android.internal.app.ActionBarImpl$ActionModeImpl.onMenuItemSelected(ActionBarImpl.java:969)
        at com.android.internal.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:735)
        at com.android.internal.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:152)
        at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:874)
        at com.android.internal.view.menu.ActionMenuView.invokeItem(ActionMenuView.java:546)
        at com.android.internal.view.menu.ActionMenuItemView.onClick(ActionMenuItemView.java:115)
        at android.view.View.performClick(View.java:4438)
        at android.view.View$PerformClick.run(View.java:18422)
        at android.os.Handler.handleCallback(Handler.java:733)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:136)
        at android.app.ActivityThread.main(ActivityThread.java:5017)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:515)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
        at dalvik.system.NativeStart.main(Native Method)
```
